### PR TITLE
CIS - Add Auditd.conf & Bug Fixes

### LINKED ISSUE #47: CIS - Add configuration to /etc/audit/audit.conf
Issue found when investigating fails on CIS Compliance Profile Centos 7 & RHEL 7 controls 4.1.1.2 & 4.1.1.3.

Currently, checks are being performed on the audit.conf file for things such as:
`
space_left_action = email
action_mail_acct = root
admin_space_left_action = halt
`

The values in the audit.conf file is currently:
`
space_left_action = SYSLOG
action_mail_acct = root
admin_space_left_action = SUSPEND
`

At the moment the auditd cookbook does not currently add/change the configuration in the `audit.conf` file.

### PR DESCRIPTION
**Pull request by rmoles**
Fixes #47 
Support has been added to update the auditd.conf to bring it in line with CIS specification. Files added as a result: cis.auditd.conf.erb, conf_file.erb, conf.rb

Changes have been made to the cis.rules.erb to fix failing Inspec controls.

### CODE REVIEW

File: recipes/conf.rb [hunk 1]
```diff
@@ -0,0 +1,22 @@
+#
+# Cookbook:: auditd
+# Recipe:: default
+#
+# Copyright:: 2012-2017, Heavy Water Operations, LLC.
```
Comment (tas50) [inline recipes/conf.rb]: This should be us now

File: resources/conf_file.rb [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
+property :cookbook, String
+
+action :create do
+  extend AuditD::Helper
+
+  template new_resource.name do
```
Comment (tas50) [inline resources/conf_file.rb]: You probably want to create a name_property here so you can do something like this

```
auditd_conf_file 'my conf file' do
  file_path '/foo/bar/'
end
```

File: templates/cis.rules.erb [hunk 3]
```diff
@@ -47,9 +47,15 @@
 -w /var/run/faillock/ -p wa -k logins
 
 # CIS 4.1.9
+<% if node['platform_version'] =~ /^6/ %>
```
Comment (tas50) [inline templates/cis.rules.erb]: Are you trying to get RHEL 6 here? This is going to match a whole bunch of platforms if written this way.

Comment (rmoles) [reply templates/cis.rules.erb]: I based this on the platform version checks for CIS 4.1.4 in the same file. It does need to allow for CentOs and RHEL. If you think this is too generic, I will need to look into refactoring CIS 4.1.4 also.

Comment (james-stocks) [reply templates/cis.rules.erb]: Tim already suggested this, but the PR he made the suggestion on got merged before it could be added:

https://github.com/chef-cookbooks/auditd/pull/43#discussion_r203082747

> A better thing to do here is node['platform_version'].to_i == 6

File: templates/cis.auditd.conf.erb [hunk 4]
```diff
@@ -0,0 +1,35 @@
...
+dispatcher = /sbin/audispd
+name_format = NONE
+max_log_file_action = keep_logs
+space_left = 75
+space_left_action = email
+action_mail_acct = root
+admin_space_left = 50
+admin_space_left_action = halt
+disk_full_action = SUSPEND
+disk_error_action = SUSPEND
```
Comment (james-stocks) [inline templates/cis.auditd.conf.erb]: Having the entire file Chef-managed will prevent users from being able to adjust any of these settings. I'm not sure anyone is likely to want/need to adjust any of these though.
I think this change is good - if anyone wants any of these adjustable, we can add attributes later.

It would also be cool (but again, can do it later) to add comments to any lines of config that map to a CIS recommendation

File: metadata.rb [hunk 5]
```diff
@@ -4,7 +4,7 @@
 license 'Apache-2.0'
 description 'Installs/Configures auditd'
 long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
-version '2.3.3'
+version '2.4.0'
```
Comment (coderanger) [inline metadata.rb]: Don't change versions in a feature PR.

File: recipes/conf.rb [hunk 6]
```diff
@@ -0,0 +1,22 @@
+#
+# Cookbook:: auditd
+# Recipe:: default
+#
+# Copyright:: 2018, Chef Software, Inc.
```
Comment (coderanger) [inline recipes/conf.rb]: Is this intentional?

File: resources/conf_file.rb [hunk 7]
```diff
@@ -0,0 +1,35 @@
+
```
Comment (coderanger) [inline resources/conf_file.rb]: Blank line.

File: metadata.rb (hunk 5 above)
Comment (chris-rock) [reply metadata.rb]: I agree with @coderanger PRs should not bump the version number

File: recipes/conf.rb (hunk 6 above)
Comment (chris-rock) [reply recipes/conf.rb]: I also agree that we should not add this here

File: templates/cis.auditd.conf.erb [hunk 8]
```diff
@@ -0,0 +1,35 @@
+#
+# This file is managed using Chef. Any changes will be overwritten.
+#
+# This file controls the configuration of the audit daemon
+#
+
+local_events = yes
```
[the remark this answers is not in the document]
Comment (chris-rock) [reply templates/cis.auditd.conf.erb]: I agree that those values should be user configurable. We can use a template to render the values but that is all we should do as part of the PR. We should not add Chef internal values as part of this cookbook.

File: templates/cis.rules.erb [hunk 9]
```diff
@@ -12,7 +12,6 @@
 
 # Feel free to add below this line. See auditctl man page
 
-
 # CIS Benchmark Adjustments
```
Comment (chris-rock) [inline templates/cis.rules.erb]: This cookbook is intended to focus on general implementation. Tie it to CIS is not a good idea.

File: recipes/conf.rb (hunk 6 above)
Comment (tas50) [reply recipes/conf.rb]: If we're shipping it we should add our copyright so this is entirely appropriate

**Comment by rmoles** [comment]
@tas50 Changes have been made based on comments. It would be good to get your opinion on this.

File: resources/conf_file.rb [hunk 10]
```diff
@@ -1,35 +1,15 @@
-
 #
 # Cookbook:: auditd
 # Resource:: auditd_conf_file
-#
```
Comment (tas50) [inline resources/conf_file.rb]: We do actually want this. I think the original comment saying to remove it in confusion.

**Comment by tas50** [comment]
My overall concern with this resource is what the end goal is. A resource that just drops off a file where the user doesn't control the content isn't really a resource. That's just a file/template in a recipe. If we were to fast forward a year what does this resource offer to a user? How can they use / reuse it throughout their infrastructure? If the answer is that only this cookbook ever consumes it and we use it to drop off that single config then we should just do that in a recipe and save the extra code.
